server:
  port: 8081
  #使用undertow作为服务器中间件，较Tomcat高并发时性能更好
  undertow:
    threads:
      io: 2 #cpu核心数
      worker: 16 #io线程*8
    buffer-size:  1024
    direct-buffers: true

spring:
  profiles: dev
  cloud:
    nacos:
      #nacos 使用nacos配置中心
      config:
        enabled: true

      discovery:
        #nacos 服务注册中心地址
        server-addr: 106.52.188.209:8848
        group: demo
        username: lizhao
        password: 19960214
    #
    #    circuitbreaker:
    #      hystrix:
    #        enabled: true
    #
    datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://106.52.188.209:3306/dev?useAffectedRows=true&characterEncoding=utf8&useSSL=false&rewriteBatchedStatements=true&serverTimezone=GMT%2B8&allowMultiQueries=true
      username: dev
      password: 19960214

    flyway:
      user: dev
      password: 19960214
  #    url:

  logging:
    #日志级别
    level:
      root: info
    #日志输出格式
    pattern:
      console: '%clr(%d{${LOG_DATEFORMAT_PATTERN:-yyyy-MM-dd HH:mm:ss.SSS}}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}'
      file: '%d{${LOG_DATEFORMAT_PATTERN:-yyyy-MM-dd HH:mm:ss.SSS}} ${LOG_LEVEL_PATTERN:-%5p} ${PID:- } --- [%t] %-40.40logger{39}:%m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}'
    #日志文件
    file:
      #指定日志文件 绝对路径，比path的权重更高
      name: log/cloud-gateway.log
      #只可以指定日志文件存放的路径
      path: D://appLogs