server:
  port: 8081
  #使用undertow作为服务器中间件，较Tomcat高并发时性能更好
  undertow:
    threads:
      io: 2 #cpu核心数
      worker: 16 #io线程*8
    buffer-size:  1024
    direct-buffers: true

spring:
  profiles:
    active: dev

  cloud:
    gateway:
      enabled: true
      httpclient:
        connect-timeout: 3000
        response-timeout: 5s