spring:
  devtools:
    add-properties: true
  config:
    activate:
      # 当前配置文件名称
      on-profile:
        - dev
    #
    #    circuitbreaker:
    #      hystrix:
    #        enabled: true
    #
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://106.52.188.209:3306/dev?useAffectedRows=true&characterEncoding=utf8&useSSL=false&rewriteBatchedStatements=true&serverTimezone=GMT%2B8&allowMultiQueries=true
    username: dev
    password: 19960214
  data:
    redis:
      host: localhost
      port: 6379
      client-name: gateway
      client-type: lettuce
      lettuce:
        pool:
          enabled: true
          max-active: 8
          max-idle: 8
          max-wait: -1ms
        shutdown-timeout: 100ms
#  data:
#    redis:
#      repositories:
#        enabled: true
#    mongodb:
#      host: 127.0.0.1
#      port: 27017
#      database: test

#    flyway:
#      user: dev
#      password: 19960214
#      url:
springdoc:
  api-docs:
    enabled: true
    version: OPENAPI_3_0
  swagger-ui:
    enabled: true
    path: v3/api-doc.html

#  logging:
#    #日志级别
#    level:
#      root: info
#    #日志输出格式
#    pattern:
#      console: '%clr(%d{${LOG_DATEFORMAT_PATTERN:-yyyy-MM-dd HH:mm:ss.SSS}}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}'
#      file: '%d{${LOG_DATEFORMAT_PATTERN:-yyyy-MM-dd HH:mm:ss.SSS}} ${LOG_LEVEL_PATTERN:-%5p} ${PID:- } --- [%t] %-40.40logger{39}:%m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}'
#    #日志文件
#    file:
#      #指定日志文件 绝对路径，比path的权重更高
#      name: log/cloud-gateway.log
#      #只可以指定日志文件存放的路径
#      path: D://appLogs
