spring:
  devtools:
    add-properties: true
  config:
    activate:
      # 当前配置文件名称
      on-profile:
        - dev
    #
    #    circuitbreaker:
    #      hystrix:
    #        enabled: true
    #
#  # MQ
#  rabbitmq:
#    host: 106.52.188.209
#    port: 5672
#    virtual-host: gateway
#    username: gateway
#    password: 19960214
  kafka: # 其他配置在 application.yml
    bootstrap-servers:
      - 106.52.188.209:9092
  data:
    redis:
      repositories:
        enabled: true
      host: 106.52.188.209
      port: 6379
      database: 0
      username: gateway
      password: 19960214
      client-name: gateway
      client-type: LETTUCE
      lettuce:
        pool:
          enabled: true
          max-active: 8
          max-idle: 8
          max-wait: -1ms
        shutdown-timeout: 100ms
  r2dbc:
    #    username: gateway
    #    password: 19960214
    url: r2dbc:postgresql://gateway_dev_01:19960214@106.52.188.209:5432/gateway
    properties:
      currentSchema: gateway_dev # 设置 schema
    pool:
      validation-query: select 1=1 from "user"
      enabled: true
      initial-size: 10
# r2dbc 不支持jpa
#  jpa:
#    database: PostgreSQL
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
#    hibernate:
#      naming:
#        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
#      ddl-auto: update # DDL 级别 (create, create-drop, validate, update) none
#    properties:
#      hibernate:
#        auto_quote_keyword: true
#        dialect: org.hibernate.dialect.PostgreSQLDialect
#        default_schema: dev
#    show-sql: true
  # 多数据源配置
#  datasource:
#    driver-class-name: org.postgresql.Driver

# json web token 密钥 org.lizhao.base.utils.JwtUtils
web:
  jwt:
    key: 0F2F50B9C91B608842353348223BB61DC6D378564F66162E1D6B233307E467DF

#    flyway:
#      user: dev
#      password: 19960214
#      url:

#logging:
##  config: log4j2.xml
#  #日志级别
#  level:
#    root: info
#    #日志输出格式
#    pattern:
#      console: '%clr(%d{${LOG_DATEFORMAT_PATTERN:-yyyy-MM-dd HH:mm:ss.SSS}}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}'
#      file: '%d{${LOG_DATEFORMAT_PATTERN:-yyyy-MM-dd HH:mm:ss.SSS}} ${LOG_LEVEL_PATTERN:-%5p} ${PID:- } --- [%t] %-40.40logger{39}:%m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}'
#    #日志文件
#    file:
#      #指定日志文件 绝对路径，比path的权重更高
#      name: log/cloud-gateway.log
#      #只可以指定日志文件存放的路径
#      path: D://appLogs
