server:
  port: 8081
  servlet:
    context-path: /gateway
  netty:
    max-keep-alive-requests: 10000
    connection-timeout: 30

# gateway 配置
management:
  endpoint:
    mappings:
      enabled: true
    gateway: #endpoint id
      enabled: true # 开启对应的endpoint
    health:
      show-details: always
  endpoints: # 管理终端配置 不开放给外部使用（仅供内部人员或运维人员） spring EndPoint
    web:
      cors:
        allowed-origins:
          - 127.0.0.1
      base-path: /actuator # 上下文路径
      exposure:
        include:
         - 'gateway' # 暴露所有的endPoint

spring:
  profiles:
    #起效的配置文件后缀 application-xxx，maven配置
    active: @maven.spring.env@
  output:
    ansi:
      enabled: ALWAYS
  cloud:
    gateway:
      enabled: true
      redis:
        enabled: true #org.springframework.cloud.gateway.config.GatewayRedisAutoConfiguration
      redis-route-definition-repository:
        enabled: true #org.springframework.cloud.gateway.config.GatewayRedisAutoConfiguration##org.springframework.cloud.gateway.config.GatewayRedisAutoConfiguration
      httpclient:
        connect-timeout: 3000
        response-timeout: 5s
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

springdoc:
  api-docs:
    enabled: true
    version: OPENAPI_3_0
  swagger-ui:
    enabled: true
    path: /swagger.html
