spring:
  devtools:
    add-properties: true
  config:
    activate:
      # 当前配置文件名称
      on-profile:
        - dev
    #
    #    circuitbreaker:
    #      hystrix:
    #        enabled: true
    #
  r2dbc:
    url: r2dbc:postgresql://gateway:19960214@localhost:5432/gateway
#    username: gateway
#    password: 19960214
    pool:
      enabled: true
      initial-size: 10
  data:
    redis:
      repositories:
        enabled: true
      host: 106.52.188.209
      port: 6379
      database: 0
      username: gateway
      password: 123456
      client-name: gateway
      client-type: LETTUCE
      lettuce:
        pool:
          enabled: true
          max-active: 8
          max-idle: 8
          max-wait: -1ms
        shutdown-timeout: 100ms
    mongodb:
      host: 106.52.188.209
      port: 27017
      database: gateway
      username: lizhao
      password: 19960214

#    flyway:
#      user: dev
#      password: 19960214
#      url:

#logging:
##  config: log4j2.xml
#  #日志级别
#  level:
#    root: info
#    #日志输出格式
#    pattern:
#      console: '%clr(%d{${LOG_DATEFORMAT_PATTERN:-yyyy-MM-dd HH:mm:ss.SSS}}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}'
#      file: '%d{${LOG_DATEFORMAT_PATTERN:-yyyy-MM-dd HH:mm:ss.SSS}} ${LOG_LEVEL_PATTERN:-%5p} ${PID:- } --- [%t] %-40.40logger{39}:%m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}'
#    #日志文件
#    file:
#      #指定日志文件 绝对路径，比path的权重更高
#      name: log/cloud-gateway.log
#      #只可以指定日志文件存放的路径
#      path: D://appLogs
