server:
  port: 8081
  servlet:
    context-path: /gateway
  netty:
    max-keep-alive-requests: 10000
    connection-timeout: 30

spring:
  output:
    ansi:
      enabled: ALWAYS
  profiles:
    #起效的配置文件后缀 application-xxx，maven配置
    active: @maven.spring.env@
  cloud:
    gateway:
      enabled: true
      redis:
        enabled: true #org.springframework.cloud.gateway.config.GatewayRedisAutoConfiguration
      redis-route-definition-repository:
        enabled: true #org.springframework.cloud.gateway.config.GatewayRedisAutoConfiguration##org.springframework.cloud.gateway.config.GatewayRedisAutoConfiguration
      httpclient:
        connect-timeout: 3000
        response-timeout: 5s
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

springdoc:
  api-docs:
    enabled: true
    version: OPENAPI_3_0
  swagger-ui:
    enabled: true
    path: /swagger.html
